spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: an902318
    url: jdbc:mysql://localhost:3306/otatime

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: UTC
        format_sql: true   # SQL 포맷팅을 활성화

redis:
  host: localhost
  port: 6379
  password:
